-- Guard against databases that do not yet have the leave type lookup table.
-- V130 creates this table, but keeping the definition here makes V132 safe to
-- apply on existing schemas that are missing that migration.
CREATE TABLE IF NOT EXISTS leave_types (
    id BIGSERIAL PRIMARY KEY,
    school_id BIGINT NOT NULL,
    designation_id BIGINT,
    applicant_type VARCHAR(50) NOT NULL,
    leave_type VARCHAR(255) NOT NULL,
    allowed_leaves_per_year INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_leave_types_school_id ON leave_types (school_id);
CREATE INDEX IF NOT EXISTS idx_leave_types_designation_id ON leave_types (designation_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leave_types_school_applicant_designation_leave
    ON leave_types (school_id, applicant_type, COALESCE(designation_id, -1), lower(leave_type));

CREATE TABLE leave_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    head_office_id BIGINT,
    academic_year VARCHAR(20) NOT NULL,
    applicant_type VARCHAR(50) NOT NULL,
    designation_id BIGINT,
    designation_name VARCHAR(255),
    applicant_id BIGINT NOT NULL,
    applicant_name VARCHAR(255) NOT NULL,
    leave_type_id BIGINT NOT NULL,
    leave_type_name VARCHAR(255) NOT NULL,
    application_date DATE NOT NULL,
    leave_from DATE NOT NULL,
    leave_to DATE NOT NULL,
    leave_reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attachment_name TEXT,
    attachment_url TEXT,
    attachment_type TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leave_app_school FOREIGN KEY (school_id) REFERENCES schools(id),
    CONSTRAINT fk_leave_app_designation FOREIGN KEY (designation_id) REFERENCES designations(id),
    CONSTRAINT fk_leave_app_leave_type FOREIGN KEY (leave_type_id) REFERENCES leave_types(id)
);

CREATE INDEX idx_leave_app_school_status ON leave_applications (school_id, status);
CREATE INDEX idx_leave_app_applicant ON leave_applications (applicant_id);
