ALTER TABLE students ADD COLUMN IF NOT EXISTS father_email VARCHAR(150);
ALTER TABLE students ADD COLUMN IF NOT EXISTS mother_email VARCHAR(150);
ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_email VARCHAR(150);

