CREATE TABLE IF NOT EXISTS payment_settings (
    id BIGSERIAL PRIMARY KEY,
    head_office_id BIGINT,
    school_id BIGINT NOT NULL,
    school_name VARCHAR(255),
    gateway VARCHAR(100) NOT NULL,
    paypal_email VARCHAR(255),
    secret_key VARCHAR(500),
    publishable_key VARCHAR(500),
    payumoney_key VARCHAR(500),
    key_salt VARCHAR(500),
    merchant_id VARCHAR(500),
    working_key VARCHAR(500),
    access_code VARCHAR(500),
    merchant_key VARCHAR(500),
    merchant_mid VARCHAR(500),
    website VARCHAR(500),
    industry_type VARCHAR(255),
    public_key VARCHAR(500),
    password VARCHAR(500),
    store_id VARCHAR(500),
    user_id VARCHAR(500),
    submer_name VARCHAR(255),
    submer_id VARCHAR(500),
    terminal_id VARCHAR(500),
    client_key VARCHAR(500),
    server_key VARCHAR(500),
    api_key VARCHAR(500),
    auth_token VARCHAR(500),
    vendor_id VARCHAR(500),
    hash_key VARCHAR(500),
    is_demo VARCHAR(10) NOT NULL DEFAULT 'Yes',
    extra_charge VARCHAR(50),
    is_active VARCHAR(10) NOT NULL DEFAULT 'No',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
