-- ============================================================
-- Flyway Migration V279: RBAC Module → Function → CRUD Matrix
-- ============================================================

-- Create tables
CREATE TABLE IF NOT EXISTS rbac_modules (
  id       SERIAL PRIMARY KEY,
  name     VARCHAR(100) NOT NULL UNIQUE,
  order_no INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rbac_functions (
  id        SERIAL PRIMARY KEY,
  module_id INT NOT NULL REFERENCES rbac_modules(id) ON DELETE CASCADE,
  name      VARCHAR(100) NOT NULL,
  slug      VARCHAR(100) NOT NULL UNIQUE,
  order_no  INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rbac_role_page_permissions (
  id          SERIAL PRIMARY KEY,
  role_name   VARCHAR(100) NOT NULL,
  school_id   BIGINT REFERENCES schools(id) ON DELETE CASCADE,
  function_id INT NOT NULL REFERENCES rbac_functions(id) ON DELETE CASCADE,
  can_view    BOOLEAN NOT NULL DEFAULT false,
  can_add     BOOLEAN NOT NULL DEFAULT false,
  can_edit    BOOLEAN NOT NULL DEFAULT false,
  can_delete  BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (role_name, school_id, function_id)
);

-- Seed Modules
INSERT INTO rbac_modules (id, name, order_no) VALUES
(1, 'Core System', 1),
(2, 'Administrator', 2),
(3, 'Student Management', 3),
(4, 'Academic Management', 4),
(5, 'Teacher', 5),
(6, 'Lesson Plan', 6),
(7, 'Examination System', 7),
(8, 'Human Resource', 8),
(9, 'Finance & Accounts', 9),
(10, 'Communication', 10),
(11, 'Certificates', 11),
(12, 'Other', 12)
ON CONFLICT (name) DO NOTHING;

SELECT setval('rbac_modules_id_seq', (SELECT MAX(id) FROM rbac_modules));

-- Seed Functions (Total: 251)
INSERT INTO rbac_functions (module_id, name, slug, order_no) VALUES
(12, 'About School', 'about-school', 1),
(12, 'About School Edit', 'about-school-edit', 2),
(10, 'Absent Email', 'absent-email', 3),
(12, 'Absent Sms', 'absent-sms', 4),
(2, 'Academic Year', 'academic-year', 5),
(12, 'Accounting Balance Report', 'accounting-balance-report', 6),
(10, 'Add Absent Email', 'add-absent-email', 7),
(12, 'Add Asset Item', 'add-asset-item', 8),
(12, 'Add Asset Purchase', 'add-asset-purchase', 9),
(12, 'Add Asset Store', 'add-asset-store', 10),
(12, 'Add Asset Vendor', 'add-asset-vendor', 11),
(4, 'Add Assignment', 'add-assignment', 12),
(12, 'Add Bulk Invoice', 'add-bulk-invoice', 13),
(12, 'Add Call Log', 'add-call-log', 14),
(12, 'Add Class Lecture', 'add-class-lecture', 15),
(12, 'Add Complain', 'add-complain', 16),
(12, 'Add Donor', 'add-donor', 17),
(12, 'Add Event', 'add-event', 18),
(12, 'Add Expenditure', 'add-expenditure', 19),
(12, 'Add Fee Collection', 'add-fee-collection', 20),
(12, 'Add Gallery', 'add-gallery', 21),
(12, 'Add Guardian', 'add-guardian', 22),
(12, 'Add Holiday', 'add-holiday', 23),
(12, 'Add Issue', 'add-issue', 24),
(12, 'Add Leave Application', 'add-leave-application', 25),
(12, 'Add Leave Type', 'add-leave-type', 26),
(12, 'Add Lesson', 'add-lesson', 27),
(12, 'Add Live Class', 'add-live-class', 28),
(12, 'Add Manage Designation', 'add-manage-designation', 29),
(12, 'Add Manage Employee', 'add-manage-employee', 30),
(12, 'Add News', 'add-news', 31),
(12, 'Add Notice', 'add-notice', 32),
(12, 'Add Online Exam', 'add-online-exam', 33),
(12, 'Add Opening Hour', 'add-opening-hour', 34),
(12, 'Add Postal Dispatch', 'add-postal-dispatch', 35),
(12, 'Add Postal Receive', 'add-postal-receive', 36),
(12, 'Add Purchase', 'add-purchase', 37),
(12, 'Add Question Bank', 'add-question-bank', 38),
(12, 'Add Room', 'add-room', 39),
(12, 'Add Salary Grade', 'add-salary-grade', 40),
(12, 'Add Scholarship', 'add-scholarship', 41),
(12, 'Add School', 'add-school', 42),
(12, 'Add Student', 'add-student', 43),
(12, 'Add Student Activity', 'add-student-activity', 44),
(4, 'Add Study Material', 'add-study-material', 45),
(12, 'Add Subject', 'add-subject', 46),
(12, 'Add Submission', 'add-submission', 47),
(12, 'Add Super Admin', 'add-super-admin', 48),
(4, 'Add Syllabus', 'add-syllabus', 49),
(12, 'Add Teacher', 'add-teacher', 50),
(12, 'Add Topic', 'add-topic', 51),
(12, 'Add Vendor', 'add-vendor', 52),
(10, 'Add Videos', 'add-videos', 53),
(12, 'Add Visitor Info', 'add-visitor-info', 54),
(11, 'Admit Card Setting', 'admit-card-setting', 55),
(12, 'Admit Card Setting Create', 'admit-card-setting-create', 56),
(8, 'Approved Application', 'approved-application', 57),
(12, 'Asset Category', 'asset-category', 58),
(12, 'Asset Issue', 'asset-issue', 59),
(12, 'Asset Item', 'asset-item', 60),
(12, 'Asset Purchase', 'asset-purchase', 61),
(12, 'Asset Report', 'asset-report', 62),
(12, 'Asset Return', 'asset-return', 63),
(12, 'Asset Store', 'asset-store', 64),
(12, 'Asset Vendor', 'asset-vendor', 65),
(4, 'Assignment', 'assignment', 66),
(7, 'Attendance', 'attendance', 67),
(12, 'Backup Database', 'backup-database', 68),
(12, 'Book', 'book', 69),
(12, 'Book Create', 'book-create', 70),
(12, 'Books List', 'books-list', 71),
(12, 'Bulk Admission', 'bulk-admission', 72),
(10, 'Call Log', 'call-log', 73),
(11, 'Candidate', 'candidate', 74),
(12, 'Candidate Create', 'candidate-create', 75),
(12, 'Category', 'category', 76),
(11, 'Certificate Type', 'certificate-type', 77),
(12, 'Certificate Type Create', 'certificate-type-create', 78),
(4, 'Class', 'class', 79),
(5, 'Class Lecture', 'class-lecture', 80),
(6, 'Class Routine', 'class-routine', 81),
(10, 'Complain Type', 'complain-type', 82),
(12, 'Daily Statement Report', 'daily-statement-report', 83),
(12, 'Daily Transaction Report', 'daily-transaction-report', 84),
(8, 'Declined Application', 'declined-application', 85),
(9, 'Discount', 'discount', 86),
(11, 'Donar', 'donar', 87),
(12, 'Due Fee Email', 'due-fee-email', 88),
(12, 'Due Fee Report', 'due-fee-report', 89),
(12, 'Due Fee Sms', 'due-fee-sms', 90),
(9, 'Due Invoice', 'due-invoice', 91),
(12, 'Due Receipt', 'due-receipt', 92),
(12, 'Ebook', 'ebook', 93),
(12, 'Ebook Create', 'ebook-create', 94),
(12, 'Ebook List', 'ebook-list', 95),
(12, 'Edit Lesson', 'edit-lesson', 96),
(12, 'Email', 'email', 97),
(12, 'Email Create', 'email-create', 98),
(12, 'Email Setting', 'email-setting', 99),
(12, 'Email Setting Create', 'email-setting-create', 100),
(12, 'Employee Attendance', 'employee-attendance', 101),
(8, 'Employee Attendance Report', 'employee-attendance-report', 102),
(12, 'Employee Yearly Attendance Report', 'employee-yearly-attendance-report', 103),
(10, 'Event', 'event', 104),
(7, 'Exam Final Result', 'exam-final-result', 105),
(7, 'Exam Grade', 'exam-grade', 106),
(7, 'Exam Instruction', 'exam-instruction', 107),
(7, 'Exam Result', 'exam-result', 108),
(12, 'Exam Result Report', 'exam-result-report', 109),
(7, 'Exam Term', 'exam-term', 110),
(7, 'Exam Term Result', 'exam-term-result', 111),
(12, 'Expenditure', 'expenditure', 112),
(12, 'Expenditure Head', 'expenditure-head', 113),
(12, 'Expenditure Report', 'expenditure-report', 114),
(12, 'Faq', 'faq', 115),
(9, 'Fee Collection', 'fee-collection', 116),
(12, 'Fee Collection Report', 'fee-collection-report', 117),
(9, 'Fee Type', 'fee-type', 118),
(12, 'Frontend Page', 'frontend-page', 119),
(12, 'Frontend Page Create', 'frontend-page-create', 120),
(10, 'Gallery', 'gallery', 121),
(2, 'General Settings', 'general-settings', 122),
(11, 'Generate Certificate', 'generate-certificate', 123),
(11, 'Guardian', 'guardian', 124),
(1, 'Head Office Dashboard', 'head-office-dashboard', 125),
(2, 'Head Offices', 'head-offices', 126),
(10, 'Holiday', 'holiday', 127),
(12, 'Hostel Create', 'hostel-create', 128),
(12, 'Hostel Member', 'hostel-member', 129),
(11, 'Id Card Setting', 'id-card-setting', 130),
(10, 'Images', 'images', 131),
(12, 'Images Add', 'images-add', 132),
(12, 'Income', 'income', 133),
(12, 'Income Head', 'income-head', 134),
(12, 'Income Report', 'income-report', 135),
(12, 'Invoice Report', 'invoice-report', 136),
(12, 'Issue', 'issue', 137),
(12, 'Issue Book Create', 'issue-book-create', 138),
(12, 'Issue Return', 'issue-return', 139),
(8, 'Leave Application', 'leave-application', 140),
(8, 'Leave Type', 'leave-type', 141),
(6, 'Lesson', 'lesson', 142),
(6, 'Lesson Plan', 'lesson-plan', 143),
(6, 'Lesson Status', 'lesson-status', 144),
(6, 'Lesson Timeline', 'lesson-timeline', 145),
(12, 'Library Members', 'library-members', 146),
(12, 'Library Report', 'library-report', 147),
(4, 'Live Class', 'live-class', 148),
(1, 'Lms Dashboard', 'lms-dashboard', 149),
(12, 'Manage Award', 'manage-award', 150),
(12, 'Manage Award Create', 'manage-award-create', 151),
(10, 'Manage Complain', 'manage-complain', 152),
(8, 'Manage Designation', 'manage-designation', 153),
(8, 'Manage Employee', 'manage-employee', 154),
(12, 'Manage Feedback', 'manage-feedback', 155),
(12, 'Manage Hostel', 'manage-hostel', 156),
(9, 'Manage Invoice', 'manage-invoice', 157),
(7, 'Manage Mark', 'manage-mark', 158),
(12, 'Manage Room', 'manage-room', 159),
(2, 'Manage School', 'manage-school', 160),
(12, 'Manage Super Admin', 'manage-super-admin', 161),
(5, 'Manage Teacher', 'manage-teacher', 162),
(12, 'Manage Todo', 'manage-todo', 163),
(12, 'Manage Todo Create', 'manage-todo-create', 164),
(7, 'Mark Send Email', 'mark-send-email', 165),
(12, 'Mark Send Email Create', 'mark-send-email-create', 166),
(7, 'Mark Send Sms', 'mark-send-sms', 167),
(7, 'Mark Send Sms Create', 'mark-send-sms-create', 168),
(7, 'Mark Sheet', 'mark-sheet', 169),
(7, 'Merit List', 'merit-list', 170),
(10, 'News', 'news', 171),
(12, 'Non Hostel Member', 'non-hostel-member', 172),
(12, 'Non Library Members', 'non-library-members', 173),
(12, 'Non Transport Member', 'non-transport-member', 174),
(10, 'Notice', 'notice', 175),
(3, 'Online Admission', 'online-admission', 176),
(7, 'Onlineexam', 'onlineexam', 177),
(12, 'Opening Hour', 'opening-hour', 178),
(12, 'Paid Receipt', 'paid-receipt', 179),
(1, 'Parent Dashboard', 'parent-dashboard', 180),
(2, 'Payment Setting', 'payment-setting', 181),
(2, 'Payment Setting Create', 'payment-setting-create', 182),
(12, 'Payroll Report', 'payroll-report', 183),
(10, 'Postal Dispatch', 'postal-dispatch', 184),
(10, 'Postal Receive', 'postal-receive', 185),
(12, 'Product', 'product', 186),
(12, 'Promotion', 'promotion', 187),
(12, 'Purchase', 'purchase', 188),
(7, 'Question Bank', 'question-bank', 189),
(5, 'Rating', 'rating', 190),
(7, 'Result Card', 'result-card', 191),
(7, 'Result Email', 'result-email', 192),
(7, 'Result Email Create', 'result-email-create', 193),
(7, 'Result Sms', 'result-sms', 194),
(7, 'Result Sms Create', 'result-sms-create', 195),
(8, 'Salary Grade', 'salary-grade', 196),
(8, 'Salary History', 'salary-history', 197),
(8, 'Salary Payment', 'salary-payment', 198),
(12, 'Sale', 'sale', 199),
(12, 'Sale Create', 'sale-create', 200),
(7, 'Schedule', 'schedule', 201),
(12, 'Schedule Create', 'schedule-create', 202),
(11, 'Scholarship', 'scholarship', 203),
(1, 'School Admin Dashboard', 'school-admin-dashboard', 204),
(12, 'School Subscription', 'school-subscription', 205),
(4, 'Section', 'section', 206),
(12, 'Slider', 'slider', 207),
(12, 'Slider Create', 'slider-create', 208),
(12, 'Sms', 'sms', 209),
(12, 'Sms Create', 'sms-create', 210),
(2, 'Sms Setting', 'sms-setting', 211),
(2, 'Sms Setting Create', 'sms-setting-create', 212),
(3, 'Student Activity', 'student-activity', 213),
(12, 'Student Activity Report', 'student-activity-report', 214),
(3, 'Student Attendance', 'student-attendance', 215),
(12, 'Student Attendance Report', 'student-attendance-report', 216),
(1, 'Student Dashboard', 'student-dashboard', 217),
(12, 'Student Invoice Report', 'student-invoice-report', 218),
(3, 'Student List', 'student-list', 219),
(12, 'Student Report', 'student-report', 220),
(3, 'Student Type', 'student-type', 221),
(12, 'Student Yearly Attendance Report', 'student-yearly-attendance-report', 222),
(4, 'Study Material', 'study-material', 223),
(4, 'Subject', 'subject', 224),
(4, 'Submission', 'submission', 225),
(12, 'Subscription Faq', 'subscription-faq', 226),
(12, 'Subscription Plans', 'subscription-plans', 227),
(12, 'Subscription Settings', 'subscription-settings', 228),
(12, 'Subscription Slider', 'subscription-slider', 229),
(7, 'Suggestion', 'suggestion', 230),
(12, 'Suggestion Create', 'suggestion-create', 231),
(12, 'Super Admin Dashboard', 'super-admin-dashboard', 232),
(12, 'Supplier', 'supplier', 233),
(4, 'Syllabus', 'syllabus', 234),
(5, 'Teacher Attendance', 'teacher-attendance', 235),
(12, 'Teacher Attendance Report', 'teacher-attendance-report', 236),
(1, 'Teacher Dashboard', 'teacher-dashboard', 237),
(5, 'Teacher Department', 'teacher-department', 238),
(12, 'Teacher Yearly Attendance Report', 'teacher-yearly-attendance-report', 239),
(6, 'Topic', 'topic', 240),
(12, 'Transport Member', 'transport-member', 241),
(12, 'Transport Route', 'transport-route', 242),
(12, 'Transport Route Create', 'transport-route-create', 243),
(2, 'User Role Acl', 'user-role-acl', 244),
(12, 'Vehicle', 'vehicle', 245),
(12, 'Vehicle Create', 'vehicle-create', 246),
(10, 'Videos', 'videos', 247),
(10, 'Visitor Info', 'visitor-info', 248),
(10, 'Visitor Purpose', 'visitor-purpose', 249),
(8, 'Waiting Application', 'waiting-application', 250),
(12, 'Warehouse', 'warehouse', 251)
ON CONFLICT (slug) DO NOTHING;

SELECT setval('rbac_functions_id_seq', (SELECT MAX(id) FROM rbac_functions));
